language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: "jscaltreto"
  distributions: sdist bdist_wheel
  password:
    secure: o7pFhgwTesvJp+KpyLvBnSpxmHhvvyzrSic5+o4rF3Cf8tW6FPWpB968+emfI1vaNGQ8Kdb/uOdS6xBnBvOmZ8QMT1BHpdheRi4rr/ENZDvJkaram9l7NzMvgBAMmhz6EjbWeoJnb1VOg8LCaoevyBnMt08JAK9UgjH4K03rMAwQ2eNRdnkEJSIFIO9zNRVrUL0EurHMUgnM65ak18PmZaSVv2mrA0KZQIL9fc3gVGL10O/gIibvoUHV7mxQpzQDzAciQTpP+j9Pf/89qddsxpq2QKSvSPippmpgH41cX0TMpFLGPb23H5TOAaKpjUB1ZLCqa/9rrkZdMsupwAqw4BNNilFjbT6pcuYcGBM8eGAYteA1njjmd576+LedcMHT9oIEfePt34JjWMCN4aDcr95yp8TucOlke8vslOakSGdkC+E5KAetumQ1RbCNhV1SE/sybcmiyVkZnGxzIOLkldDY57jjSTxYV3uACSRxFpYIpzhPo6lxUvponscUsKiXDWg7m+QaoibS4P5UkPHDo68n6zgDdVt2ENoRyvF0LVqGrSKFOD87cXLeiCc3EcIkWC872QLO/I1wvABm4PckGPMSp3VDJH2qHzMiiJaUlfSSeWh50MxQdg2/xgFnTCafZdTwR8eoOfjeENGxJbBDFm/0kOq0NB62qOkYhJ7OKSw=
  on:
    tags: true
    branch: master
